# Site Settings
title: Satwiko's CV
description: The online Curriculum Vitae of Satwiko Wirawan Indrawanto
theme_skin: default

# Sass/SCSS
sass:
    sass_dir: _sass
    style: compressed

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html:
    clippings: all
    ignore:
        envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
